import Head from "next/head";
import { Inter } from "@next/font/google";
import { Input } from "@/components/input";
import { RvCard } from "@/components/rv-card";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-5">
        <Input />
        <RvCard
          rv={{
            name: "City Escapes Adventure Van - 2022 Winnebago Solis 59P, Sleeps 4, Hot Shower",
            primaryImageUrl:
              "https://res.cloudinary.com/outdoorsy/image/upload/v1655651700/p/rentals/236274/images/lscs5nvjtlgqhor8gwez.jpg",
          }}
        />
      </main>
    </>
  );
}
